//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Echipamente
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public int CategorieId { get; set; }
        public string Marime { get; set; }
        public string Descriere { get; set; }
        public decimal Pret { get; set; }
        public int UnitId { get; set; }
        public byte In_Stoc { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Unitate Unitate { get; set; }
    }
}
